#-----------------------------------------------------------------------------
#
# calquantumConfig.cmake - CMake configuration file for external projects.
# This file was automatically generated by the cmake macro 
# CREA_INSTALL_LIBRARY_FOR_CMAKE of the package CREA
#
# This file is configured by cmake and used by the
# Usecalquantum.cmake module to load the lib settings 
# for an external project.

# Build tree config ?
SET(CILC_BUILD_TREE_CONFIGURATION FALSE)


IF(UNIX)
SET(GOTO_INSTALL_PREFIX /../../..)
ENDIF(UNIX)


# The calquantum include file *RELATIVE* directories.
SET(CILC_RELATIVE_INCLUDE_PATHS "include/calquantum")
# Compute the prefix for include and library paths
IF(CILC_BUILD_TREE_CONFIGURATION)
  # In build tree 
  # the include paths are relative to the source tree *AND* the binary tree 
  # for generated files 
  SET(CILC_INCLUDE_PATH_PREFIX /playpen/workspace/newuoa/Correspondence_Oct7/Pablo2_Oct7)
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(calquantum_INCLUDE_DIRS
      ${calquantum_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
  SET(CILC_INCLUDE_PATH_PREFIX /playpen/workspace/newuoa/Correspondence_Oct7/myBuild)
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(calquantum_INCLUDE_DIRS
      ${calquantum_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
ELSE(CILC_BUILD_TREE_CONFIGURATION)
  # In install tree 
  # the include paths are relative to install prefix 
  # On unix , GOTO_INSTALL_PREFIX allows to get back to the 
  # installation prefix from  calquantum_DIR
  SET(CILC_INCLUDE_PATH_PREFIX ${calquantum_DIR}${GOTO_INSTALL_PREFIX})
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(calquantum_INCLUDE_DIRS
      ${calquantum_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
ENDIF(CILC_BUILD_TREE_CONFIGURATION)



# Compute the prefix for library paths
IF(CILC_BUILD_TREE_CONFIGURATION)
  # In build tree
  # the library paths are relative to the binary tree 
  SET(CILC_LIBRARY_PATH_PREFIX /playpen/workspace/newuoa/Correspondence_Oct7/myBuild)
ELSE(CILC_BUILD_TREE_CONFIGURATION)
  # In install tree 
  # the library paths are relative to install prefix
  SET(CILC_LIBRARY_PATH_PREFIX ${calquantum_DIR}${GOTO_INSTALL_PREFIX})
ENDIF(CILC_BUILD_TREE_CONFIGURATION)
# The calquantum library file *RELATIVE* directories.
SET(CILC_RELATIVE_LIBRARY_PATHS "lib64")
# Build the *ABSOLUTE* directories
FOREACH(path ${CILC_RELATIVE_LIBRARY_PATHS})
  SET(calquantum_LIBRARY_DIRS
    ${calquantum_LIBRARY_DIRS}
    ${CILC_LIBRARY_PATH_PREFIX}/${path}
    )
ENDFOREACH(path ${CILC_RELATIVE_LIBRARY_PATHS})

# Set the "prefix path"
SET(calquantum_INSTALL_PREFIX ${CILC_LIBRARY_PATH_PREFIX})

# The C and C++ flags added by calquantum to the cmake-configured flags.
SET(calquantum_REQUIRED_C_FLAGS "")
SET(calquantum_REQUIRED_CXX_FLAGS "")
SET(calquantum_REQUIRED_LINK_FLAGS "")

# The calquantum version 
SET(calquantum_MAJOR_VERSION )
SET(calquantum_MINOR_VERSION )
SET(calquantum_BUILD_VERSION )
SET(calquantum_VERSION ..)

# The location of the Usecalquantum.cmake file.
SET(calquantum_USE_FILE "${calquantum_DIR}/Usecalquantum.cmake")

# The build settings file.
SET(calquantum_BUILD_SETTINGS_FILE 
  "${calquantum_DIR}/calquantumBuildSettings.cmake")

# A list of all libraries for calquantum.  Those listed here should
# automatically pull in their dependencies.
SET(calquantum_LIBRARIES calquantum)

# Messages
IF(CREA_VERBOSE_CMAKE)
  MESSAGE(STATUS "=======================================")
  MESSAGE(STATUS "Looking for calquantum... found:")
  MESSAGE(STATUS "* calquantum_DIR          = ${calquantum_DIR}")
  MESSAGE(STATUS "* calquantum_VERSION      = ${calquantum_VERSION}")
  MESSAGE(STATUS "* calquantum_USE_FILE     = ${calquantum_USE_FILE}")

  MESSAGE(STATUS "* calquantum_INCLUDE_DIRS = ${calquantum_INCLUDE_DIRS}")
  MESSAGE(STATUS "* calquantum_LIBRARY_DIRS = ${calquantum_LIBRARY_DIRS}")
  MESSAGE(STATUS "* calquantum_LIBRARIES    = ${calquantum_LIBRARIES}")
ENDIF(CREA_VERBOSE_CMAKE)

# Does the library has an additional config file (user provided) ?
SET(calquantum_HAS_ADDITIONAL_CONFIG_FILE FALSE)

IF (calquantum_HAS_ADDITIONAL_CONFIG_FILE)
  IF(CREA_VERBOSE_CMAKE)
    MESSAGE(STATUS "Reading calquantum additional configuration file")
  ENDIF(CREA_VERBOSE_CMAKE)
  # Include it
  INCLUDE(${calquantum_DIR}/AdditionalcalquantumConfig.cmake)
ENDIF (calquantum_HAS_ADDITIONAL_CONFIG_FILE)
