#ifndef MAKE_WINDOWS_H
#define MAKE_WINDOWS_H


/*  This file is used by pablo.cpp.  The enumeration below is used to
	index elements of the windowProps array, which stores the coordinates
	of all user-positionable windows.
*/


#define WIN_PROPS_LEN	32

enum win_Id { MODEL_WIN, MAIN_WIN, DISPLAY_CONTROL_WIN, VISIBILITY_CONTROL_WIN,
	CONSTRAINTS_WIN, ATOM_EDITOR_WIN, CUT_PLANES_CONTROL_WIN, OPTIMIZER_CONTROL_WIN,
	INTERPOLATED_PRIMITIVE_WIN, CREST_PLANE_WIN, ATOM_PLANE_WIN, BPERP_N_PLANE_WIN,
	STARBOARD_PLANE_WIN, PORT_PLANE_WIN, INVOLUTES_PLANE_WIN, ADD_QUAD_FIGURE_WIN,
	ATTACH_SUBFIGURE_WIN, DETACH_SUBFIGURE_WIN, PREFERENCES_EDITOR_WIN,
	EDIT_MODEL_PROPERTIES_WIN, ELONGATION_WIN, EDIT_LANDMARKS_WIN, ABOUT_PABLO_WIN,
	MASK_BUILDER_WIN, OPTIMIZER_SETTINGS_WIN, MODEL_SLIDE_SHOW_WIN, REGULARIZER_WIN,
	MATCH_SURFACES_WIN, IMAGE_PREFS_EDITOR_WIN, CPNS_DEFORMATION_WIN, PGA_DEFORMATION_WIN,
	PCA_DEFORMATION_WIN, OPT_VISUALIZER_WIN
};



#endif	/* MAKE_WINDOWS_H */

