function d = squaredNorm(symPrim)

d = sum((symPrim.pos).*(symPrim.pos)) + symPrim.r * symPrim.r + ...
    sum((symPrim.Up1) .* (symPrim.Up1)) + sum((symPrim.Um1) .* (symPrim.Um1)) + ...
    symPrim.elongation * symPrim.elongation ;