#-----------------------------------------------------------------------------
#
# versionConfig.cmake - CMake configuration file for external projects.
# This file was automatically generated by the cmake macro 
# CREA_INSTALL_LIBRARY_FOR_CMAKE of the package CREA
#
# This file is configured by cmake and used by the
# Useversion.cmake module to load the lib settings 
# for an external project.

# Build tree config ?
SET(CILC_BUILD_TREE_CONFIGURATION FALSE)


IF(UNIX)
SET(GOTO_INSTALL_PREFIX /../../..)
ENDIF(UNIX)


# The version include file *RELATIVE* directories.
SET(CILC_RELATIVE_INCLUDE_PATHS "include/version")
# Compute the prefix for include and library paths
IF(CILC_BUILD_TREE_CONFIGURATION)
  # In build tree 
  # the include paths are relative to the source tree *AND* the binary tree 
  # for generated files 
  SET(CILC_INCLUDE_PATH_PREFIX /playpen/workspace/newuoa/Correspondence_Oct7/Pablo2_Oct7)
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(version_INCLUDE_DIRS
      ${version_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
  SET(CILC_INCLUDE_PATH_PREFIX /playpen/workspace/newuoa/Correspondence_Oct7/myBuild)
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(version_INCLUDE_DIRS
      ${version_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
ELSE(CILC_BUILD_TREE_CONFIGURATION)
  # In install tree 
  # the include paths are relative to install prefix 
  # On unix , GOTO_INSTALL_PREFIX allows to get back to the 
  # installation prefix from  version_DIR
  SET(CILC_INCLUDE_PATH_PREFIX ${version_DIR}${GOTO_INSTALL_PREFIX})
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(version_INCLUDE_DIRS
      ${version_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
ENDIF(CILC_BUILD_TREE_CONFIGURATION)



# Compute the prefix for library paths
IF(CILC_BUILD_TREE_CONFIGURATION)
  # In build tree
  # the library paths are relative to the binary tree 
  SET(CILC_LIBRARY_PATH_PREFIX /playpen/workspace/newuoa/Correspondence_Oct7/myBuild)
ELSE(CILC_BUILD_TREE_CONFIGURATION)
  # In install tree 
  # the library paths are relative to install prefix
  SET(CILC_LIBRARY_PATH_PREFIX ${version_DIR}${GOTO_INSTALL_PREFIX})
ENDIF(CILC_BUILD_TREE_CONFIGURATION)
# The version library file *RELATIVE* directories.
SET(CILC_RELATIVE_LIBRARY_PATHS "lib64")
# Build the *ABSOLUTE* directories
FOREACH(path ${CILC_RELATIVE_LIBRARY_PATHS})
  SET(version_LIBRARY_DIRS
    ${version_LIBRARY_DIRS}
    ${CILC_LIBRARY_PATH_PREFIX}/${path}
    )
ENDFOREACH(path ${CILC_RELATIVE_LIBRARY_PATHS})

# Set the "prefix path"
SET(version_INSTALL_PREFIX ${CILC_LIBRARY_PATH_PREFIX})

# The C and C++ flags added by version to the cmake-configured flags.
SET(version_REQUIRED_C_FLAGS "")
SET(version_REQUIRED_CXX_FLAGS "")
SET(version_REQUIRED_LINK_FLAGS "")

# The version version 
SET(version_MAJOR_VERSION )
SET(version_MINOR_VERSION )
SET(version_BUILD_VERSION )
SET(version_VERSION ..)

# The location of the Useversion.cmake file.
SET(version_USE_FILE "${version_DIR}/Useversion.cmake")

# The build settings file.
SET(version_BUILD_SETTINGS_FILE 
  "${version_DIR}/versionBuildSettings.cmake")

# A list of all libraries for version.  Those listed here should
# automatically pull in their dependencies.
SET(version_LIBRARIES version)

# Messages
IF(CREA_VERBOSE_CMAKE)
  MESSAGE(STATUS "=======================================")
  MESSAGE(STATUS "Looking for version... found:")
  MESSAGE(STATUS "* version_DIR          = ${version_DIR}")
  MESSAGE(STATUS "* version_VERSION      = ${version_VERSION}")
  MESSAGE(STATUS "* version_USE_FILE     = ${version_USE_FILE}")

  MESSAGE(STATUS "* version_INCLUDE_DIRS = ${version_INCLUDE_DIRS}")
  MESSAGE(STATUS "* version_LIBRARY_DIRS = ${version_LIBRARY_DIRS}")
  MESSAGE(STATUS "* version_LIBRARIES    = ${version_LIBRARIES}")
ENDIF(CREA_VERBOSE_CMAKE)

# Does the library has an additional config file (user provided) ?
SET(version_HAS_ADDITIONAL_CONFIG_FILE FALSE)

IF (version_HAS_ADDITIONAL_CONFIG_FILE)
  IF(CREA_VERBOSE_CMAKE)
    MESSAGE(STATUS "Reading version additional configuration file")
  ENDIF(CREA_VERBOSE_CMAKE)
  # Include it
  INCLUDE(${version_DIR}/AdditionalversionConfig.cmake)
ENDIF (version_HAS_ADDITIONAL_CONFIG_FILE)
