#-----------------------------------------------------------------------------
#
# CorrespondenceConfig.cmake - CMake configuration file for external projects.
# This file was automatically generated by the cmake macro 
# CREA_INSTALL_LIBRARY_FOR_CMAKE of the package CREA
#
# This file is configured by cmake and used by the
# UseCorrespondence.cmake module to load the lib settings 
# for an external project.

# Build tree config ?
SET(CILC_BUILD_TREE_CONFIGURATION TRUE)


IF(UNIX)
SET(GOTO_INSTALL_PREFIX /../../..)
ENDIF(UNIX)


# The Correspondence include file *RELATIVE* directories.
SET(CILC_RELATIVE_INCLUDE_PATHS "lib/vtksrep/Correspondence")
# Compute the prefix for include and library paths
IF(CILC_BUILD_TREE_CONFIGURATION)
  # In build tree 
  # the include paths are relative to the source tree *AND* the binary tree 
  # for generated files 
  SET(CILC_INCLUDE_PATH_PREFIX /work/ltu/Correspondence_Oct7/Pablo2_Oct7)
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(Correspondence_INCLUDE_DIRS
      ${Correspondence_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
  SET(CILC_INCLUDE_PATH_PREFIX /work/ltu/Correspondence_Oct7/binPablo2_Oct7)
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(Correspondence_INCLUDE_DIRS
      ${Correspondence_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
ELSE(CILC_BUILD_TREE_CONFIGURATION)
  # In install tree 
  # the include paths are relative to install prefix 
  # On unix , GOTO_INSTALL_PREFIX allows to get back to the 
  # installation prefix from  Correspondence_DIR
  SET(CILC_INCLUDE_PATH_PREFIX ${Correspondence_DIR}${GOTO_INSTALL_PREFIX})
  # Build the *ABSOLUTE* directories
  FOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
    SET(Correspondence_INCLUDE_DIRS
      ${Correspondence_INCLUDE_DIRS}
      ${CILC_INCLUDE_PATH_PREFIX}/${path}
      )
  ENDFOREACH(path ${CILC_RELATIVE_INCLUDE_PATHS})
ENDIF(CILC_BUILD_TREE_CONFIGURATION)



# Compute the prefix for library paths
IF(CILC_BUILD_TREE_CONFIGURATION)
  # In build tree
  # the library paths are relative to the binary tree 
  SET(CILC_LIBRARY_PATH_PREFIX /work/ltu/Correspondence_Oct7/binPablo2_Oct7)
ELSE(CILC_BUILD_TREE_CONFIGURATION)
  # In install tree 
  # the library paths are relative to install prefix
  SET(CILC_LIBRARY_PATH_PREFIX ${Correspondence_DIR}${GOTO_INSTALL_PREFIX})
ENDIF(CILC_BUILD_TREE_CONFIGURATION)
# The Correspondence library file *RELATIVE* directories.
SET(CILC_RELATIVE_LIBRARY_PATHS ".")
# Build the *ABSOLUTE* directories
FOREACH(path ${CILC_RELATIVE_LIBRARY_PATHS})
  SET(Correspondence_LIBRARY_DIRS
    ${Correspondence_LIBRARY_DIRS}
    ${CILC_LIBRARY_PATH_PREFIX}/${path}
    )
ENDFOREACH(path ${CILC_RELATIVE_LIBRARY_PATHS})

# Set the "prefix path"
SET(Correspondence_INSTALL_PREFIX ${CILC_LIBRARY_PATH_PREFIX})

# The C and C++ flags added by Correspondence to the cmake-configured flags.
SET(Correspondence_REQUIRED_C_FLAGS "")
SET(Correspondence_REQUIRED_CXX_FLAGS "")
SET(Correspondence_REQUIRED_LINK_FLAGS "")

# The Correspondence version 
SET(Correspondence_MAJOR_VERSION )
SET(Correspondence_MINOR_VERSION )
SET(Correspondence_BUILD_VERSION )
SET(Correspondence_VERSION ..)

# The location of the UseCorrespondence.cmake file.
SET(Correspondence_USE_FILE "${Correspondence_DIR}/UseCorrespondence.cmake")

# The build settings file.
SET(Correspondence_BUILD_SETTINGS_FILE 
  "${Correspondence_DIR}/CorrespondenceBuildSettings.cmake")

# A list of all libraries for Correspondence.  Those listed here should
# automatically pull in their dependencies.
SET(Correspondence_LIBRARIES Correspondence)

# Messages
IF(CREA_VERBOSE_CMAKE)
  MESSAGE(STATUS "=======================================")
  MESSAGE(STATUS "Looking for Correspondence... found:")
  MESSAGE(STATUS "* Correspondence_DIR          = ${Correspondence_DIR}")
  MESSAGE(STATUS "* Correspondence_VERSION      = ${Correspondence_VERSION}")
  MESSAGE(STATUS "* Correspondence_USE_FILE     = ${Correspondence_USE_FILE}")

  MESSAGE(STATUS "* Correspondence_INCLUDE_DIRS = ${Correspondence_INCLUDE_DIRS}")
  MESSAGE(STATUS "* Correspondence_LIBRARY_DIRS = ${Correspondence_LIBRARY_DIRS}")
  MESSAGE(STATUS "* Correspondence_LIBRARIES    = ${Correspondence_LIBRARIES}")
ENDIF(CREA_VERBOSE_CMAKE)

# Does the library has an additional config file (user provided) ?
SET(Correspondence_HAS_ADDITIONAL_CONFIG_FILE FALSE)

IF (Correspondence_HAS_ADDITIONAL_CONFIG_FILE)
  IF(CREA_VERBOSE_CMAKE)
    MESSAGE(STATUS "Reading Correspondence additional configuration file")
  ENDIF(CREA_VERBOSE_CMAKE)
  # Include it
  INCLUDE(${Correspondence_DIR}/AdditionalCorrespondenceConfig.cmake)
ENDIF (Correspondence_HAS_ADDITIONAL_CONFIG_FILE)
