function drawScatPlot(data,mcolor, legendstr, markerstr, titlecellstr)
%[U S V] = svd(data);
paramstruct = struct('npcadiradd',4, ...
                       'icolor',mcolor, ...
                       'legendcellstr',legendstr,...
                       'markerstr',markerstr, ...
                       'isubpopkde',1, ...
                       'datovlaymax',0.9, ...
                       'datovlaymin',0.4, ...
                       'titlecellstr',titlecellstr, ...
                       'iscreenwrite',1) ;
scatplotSM(data,[],paramstruct) ;
end